pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Test') {
            steps {
                sh '''
                    python3 -m pip install -r app/requirements.txt
                    python3 -m pip install pytest
                    python3 -m pytest
                '''
            }
        }

        stage('Docker Build') {
            steps {
                sh '''
                    docker build \
                    -f docker/Dockerfile \
                    -t devops-cloud-platform:${BUILD_NUMBER} .
                '''
            }
        }

        stage('Docker Verify') {
            steps {
                sh 'docker images devops-cloud-platform'
            }
        }
    }
}
